### ISSUE TITLE
Problem with NXP J3H145G P60 - UNRESPONSIVE_CARD after EC_ADD operation

### ISSUE THREAD

**Issue by petrs** [OpenCryptoProject/JCMathLib#13]
Operation which causes the card to become unresponsive.
Fortunately, after around 1 minute outside reader, card becomes working again

EC Point Add:  (0)
--> B0420000820492E223622FC472D4B465F484E9926397D557E85FFFB26EEB5E42043B715605DD70B782E70E269FB0B58C45B8ACEF2ABA5B5844040B831A1848892C3315E22E460404F77A3222A39F60ACAF6EC6D724841586C178231BA768F7212309561E93D8D440C1E478C12EAAEB6B15FA19D799F263311A8A272803E47F8CB71C8E2ED1EB77
javax.smartcardio.CardException: sun.security.smartcardio.PCSCException: Unknown error 0x45d
	at java.smartcardio/sun.security.smartcardio.ChannelImpl.doTransmit(ChannelImpl.java:223)
...

**Comment by dufkan** [comment]
Resolved in [Release 2.0](https://github.com/OpenCryptoProject/JCMathLib/releases/tag/v2.0).
