### ISSUE TITLE
Create large table with supported operations on selected cards

### ISSUE THREAD

**Issue by petrs** [OpenCryptoProject/JCMathLib#17]
So far, wiki lists three cards which fully supports all JCMathLib operations. Other cards typically supports some subset as cryptographic engines refuses to perform some operations with non-standard arguments (e.g., RSA public key equal to 2 we use for acceleration of modular multiplication) or do not have enough memory to run in the fully optimized version.

Goal: Create table listing supported high-operations and identify part of code which causes faulty behaviour.

**Comment by dufkan** [comment]
Included in [Release 2.0](https://github.com/OpenCryptoProject/JCMathLib/releases/tag/v2.0).
