### ISSUE TITLE
Do you support deterministic ECDSA SHA256 (RFC6979)?

### ISSUE THREAD

**Issue by ricardovf** [OpenCryptoProject/JCMathLib#5]
Do you support deterministic ECDSA SHA256 (RFC6979)? If so, have an example? Thanks!

**Comment by petrs** [comment]
Hi,
the JCMathLib is one level below - it provides you with the ECPoint operations, not higher level operations like ECDSA SHA256 (RFC6979) you mention. However, it should be possible to construct such an operation. 

If developed, it should be placed "outside" JCMathLib and only use JCMathLib's operations (as it will add additional memory overhead). Are you thinking to attempt such an implementation?

**Comment by ricardovf** [comment]
Thanks for the answer!

I'm using non deterministic ECDSA already (bitcoin wallet project), the RFC6979 would be good for unit tests, but i check the signature with the public key on the tests, so it's not worth for me to implement this now. If i do so i'll post here.

**Comment by petrs** [comment]
ok, I see - anyway, if you will do some implementation atop of JCMathLib then we are are interested to hear any feedback - API not flexible enough, documentation confusing etc :)
